### ISSUE TITLE
Update Exercise 1.2 - Storage Size

### ISSUE THREAD

**Issue by ChrisRomp** [microsoft/TechExcel-Accelerate-developer-productivity-with-GitHub-Copilot-and-Dev-Box#16]
The lab guide says to select 256 GB SSD; however, 512 GB SSD is the smallest available (at least when I ran through the lab today). I was using West US 3 if that matters.

**Comment by feaselkl** [comment]
You're good to go. I'll make a small update to the text to clarify this.
